config/routes.rb
Rails.application.routes.draw do

  get "welcome" => "welcome#index"

  resources :reviews

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "loggedin" => "sessions#loggedin"
  delete 'sessions' => "sessions#destroy"


  resources :likes

  match 'auth/:provider/callback', to: 'sessions#create_facebook', via: [:get, :post]
  match 'auth/failure', to: redirect('login'), via: [:get, :post]
  # match 'signout', to: 'sessions#destroy_facebook', as: 'signout', via: [:get, :post]

  get 'about' => 'sessions#about'

  get "users/new" => "users#new"
  post "users" => "users#create"

  root 'welcome#index'

  get 'users/:id' => 'users#show'


   # CRUD Routes for Users and nested CRUD for reviews
   resources :users do
      resources :reviews
      end

  resources :locations




# Routes for all API views
  namespace :api do
    get 'locations_api/search_name' => 'locations_api#search_name'
    get 'locations_api/search_location' => 'locations_api#search_location'
    get 'locations_api/reviews/:id' => 'locations_api#reviews', as: :reviews
    get 'locations_api/yelp/:id' => 'locations_api#yelp', as: :yelp
    get 'locations_api/:id' => 'locations_api#show'
    resources :locations_api

  end



end

app/models/user.rb
class User < ActiveRecord::Base

  before_save :downcase_email, unless: -> { from_omniauth? }

  has_secure_password(validations: false)

  validates :username, :email, :name, :password, presence: true, unless: -> { from_omniauth? }, on: :create

  validates :email, uniqueness: { case_sensitive: false },
                    format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }, unless: -> { from_omniauth? }

  validates :password, length: { minimum: 8 }, format: { with: /\d/ }, unless: -> { from_omniauth? }


  has_many :likes, dependent: :destroy
  has_many :comments
  has_many :reviews

  mount_uploader :profile_picture, PhotoUploader

  def admin?
    self.role == 'admin'
  end

  def self.from_omniauth(auth)
    where({:provider => auth['provider'], :uid => auth['uid']}).first_or_initialize.tap do |user|
      user.provider = auth['provider']
      user.uid = auth['uid']
      user.name = auth['info']['name']
      user.oauth_token = auth['credentials']['token']
      user.oauth_expires_at = Time.at(auth['credentials']['expires_at'])
      user.save!
    end
  end

  def from_omniauth?
    provider && uid
  end

  def downcase_email
      self.email.downcase!
  end

  def has_photo_reviews?
    self.reviews.each do |review|
      if review.photo.url
        return true
      end
    end
    false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :who_is_user, only: [:edit]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Trippy "+ @user.name + "!"
      session[:user_id] = @user.id
      redirect_to locations_path
    else
      flash[:danger] = @user.errors.full_messages.to_sentence
      redirect_to welcome_path
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your profile was updated!"
      redirect_to user_path(@user)
    else
      flash[:danger] = @user.errors.full_messages.to_sentence
      render "edit"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :email, :profile_picture, :bio, :password, :password_confirmation)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!-- The file contains code for the Edit User Page -->

<!-- Begin Yielded Content -->

<div class="row">
  <div class="col-sm-12">
   <!-- Flash messages -->
     <%= render 'layouts/flash' %>
   <!-- end of flash messages -->
   </div>
</div>


<!-- <div class="row"> -->

  <div class="row">
  <div class="col-sm-3 col-sm-offset-2">
  <h1>Edit Profile</h1>
  </div>
  </div>

  <%= form_for @user, :html => { :class => "form-horizontal" } do |f| %>

    <div class="form-group">
      <%= f.label :name, class: "col-sm-3 control-label" %>
      <div class="col-sm-3">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :profile_picture, class: "col-sm-3 control-label" %>
      <div class="col-sm-3">
        <%= f.file_field :profile_picture, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email, class: "col-sm-3 control-label" %>
      <div class="col-sm-3">

        <%= f.email_field :email, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :bio, class: "col-sm-3 control-label" %>
      <div class="col-sm-3">
        <%= f.text_area :bio, placeholder: "Biography", class: "form-control", rows: "8" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password, class: "col-sm-3 control-label" %>
      <div class="col-sm-3">
        <%= f.password_field :password, placeholder: "password", class: "form-control" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation, class: "col-sm-3 control-label" %>
      <div class="col-sm-3">
        <%= f.password_field :password_confirmation, placeholder: "password", class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-3">
        <%= f.submit "Update Account", class: "btn btn-success" %>
      </div>
    </div>
 <% end %>

<!-- </div> -->

app/views/users/new.html.erb
<!-- This file contains code for the Splash/New User Page -->

<!-- Begin Yielded Page Content -->
<div class="row">
<%= render 'layouts/flash' %>

   <!-- This row contains the Image of the Phones on the left side of the page -->
  <div class="row col-xs-6 col-sm-6 col-md-6 col-lg-5 col-sm-offset-3 col-md-offset-2 col-lg-offset-0">
    <%= image_tag "phones.png", class: 'col-xs-12 col-xs-offset-8 col-sm-offset-0 col-lg-offset-2 phoneimage'%>
  </div>

  <!-- The following code block contains the text-fields and buttons on the right side of the page -->
  <div class="row">

     <!-- This is the Form for creating a new User -->
    <div class="col-xs-6 col-sm-6 col-md-4 col-lg-4 col-xs-offset-3 col-sm-offset-3 col-md-offset-2 col-lg-offset-1">

      <!-- Header -->
      <h1>Sign Up</h1>

        <!-- Following code block is the ERB form for creating a new User -->
        <%= form_for @user do |f| %>
          <br> <%= f.text_field :name, placeholder:'Name', class:'form-control' %>
          <br> <%= f.text_field :username, placeholder:'Username', class:'form-control' %>
          <br> <%= f.email_field :email, placeholder:'Email', class:'form-control' %>
          <br> <%= f.password_field :password, placeholder:'Password', class:'form-control' %>
          <br> <%= f.password_field :password_confirmation, placeholder:'Password Confirmation', class:'form-control' %><br>
          <p><%= f.submit "Create Account", class: "orange btn  col-xs-offset-2 col-sm-offset-5 col-md-offset-3 col-lg-offset-0" %></p>
        <% end %>
        <!-- End ERB form block -->
    </div>
    <!-- End of New User Form -->


    <!-- Facebook Login Code Block -->
    <div class="fbBox">

      <div class="col-xs-6 col-sm-6 col-md-3 col-lg-6 col-xs-offset-2 col-sm-offset-3 col-md-offset-1 col-lg-offset-0">

        <!-- Header -->
        <br>
        <br>
        <br>
        <br>
        <h4>Sign up through Facebook</h4>
        <h5 class='grey'>Connect and see the world</h5>

          <!-- Code block for the OAuth button for Facebook Account Creation -->
          <%= link_to "/auth/facebook" do %>
            <div class="btn btn-primary">
              Sign up with Facebook
            </div>
          <% end %>
          <!-- End of OAuth block -->

          <!-- More small text -->
            <p>Don't worry, we never post without permission</p>
      </div>
    </div>
    <!-- End of FBBOX code block -->

  </div>

</div>
<!-- End of body -->

<!-- Footer -->
<footer class="splashFooter">
  &copy Team Number One (TNO)
</footer>
<!-- End of Footer -->

<!-- End of Yielded Page Content -->

app/views/users/show.html.erb
<!-- This file contains code related to the User Profile Page -->

<!-- Begin Yielded Page Content -->
<div class="row">
<%= render 'layouts/flash' %>

  <!-- Left-Side Profile Panel -->
  <div class="biopanel col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0 col-md-4 col-md-offset-0">

    <!-- All User content displayed in this panel is in list-item format -->
    <div class="list-group left-panel">

      <div class="row text-center name">
         <h2><%= @user.name %></h2>
      </div>

      <div class="row text-center pimage">
         <%= image_tag @user.profile_picture.url || 'default_profile_pic.jpg', class: 'proimage'  %>
      </div>

      <div class="row text-center bio">
         <h3>Bio</h3>
            <%= @user.bio || "No bio added yet!" %>
      </div>

    </div>
    <!-- End of User content -->

    <!-- Edit Profile Button -->
    <div class="row text-center">
      <% if current_user.id == @user.id %>
        <%= link_to "Edit Profile", edit_user_path, class: 'btn btn-success editor' %>
      <% end %>
   </div>
   <!-- End of Profile Button -->

  </div>
  <!-- End of Biopanel code block -->

  <!-- The following code os a display of User Activity throughout the lifetime of the user -->
  <div class="col-xs-10 col-xs-offset-1 col-sm-6 col-sm-offset-0 col-md-8" id="user-activity">

    <!-- This div is/will be populated with the Reviews and Locations the User has liked -->
    <div class="like_library row">
      <h3>Starred Locations</h3>
      <% if @user.likes.any? %>
        
        <% @user.likes.each do |like| %>
          <p class="like-p"><%= link_to Location.find(like.location_id).name, location_path(like.location_id), 'data-no-turbolink' => true %>
            <%= link_to locations_path(:search => Location.find(like.location_id).name, :search_type => "Name"), 'data-no-turbolink' => true do %>
              <%= image_tag 'marker-blue.svg', class: 'mush-icon' %>
            <% end %>
            <%= link_to like, method: :delete, data: {confirm: "Are you sure you want to unlike this location?"} do %>
              <span class="glyphicon glyphicon-remove"></span>
            <% end %></p>
        <% end %>
      <% else %>
        <p>No likes yet!</p>
      <% end %>
    </div>

    <!-- This div is going to be a carousel, lol sorry Rob, of all the photos Users have submitted. If there are none, it should display "Upload a memory' in the middle of the page." -->
    <div class="photo_library row">
      <div class="col-sm-12">
        <h3 class="photo-library-header">Recently Added Pictures</h3>
        <% if @user.has_photo_reviews? %>
          <% @user.reviews.each do |review| %>
            <% if review.has_photo? %>
              <%= link_to location_path(review.location.id), 'data-no-turbolink' => true do %>
              <div class="photo-box">
                <%= image_tag review.photo.url, class: "user-photo img-thumbnail" %>
                <div class="caption">
                  <strong><%= Location.find(review.location_id).name %></strong>
                </div>
              </div>
              <% end %> <!-- end link -->
            <% end %> <!-- end has_photo? -->

          <% end %> <!-- end each review -->
        <% else %>
          <%= image_tag 'default-review-photo.jpg'%>

        <% end %>
      </div>
    </div> <!-- end photo library -->



         <!-- This div is a list of all the reviews a user has made. Again, if there are none, the page should display 'Share your opinion' in the div center-->
         <div class="review_library row">
           <div class="col-sm-12">
              <h3>Recent Reviews</h3>
              <% if @user.reviews.any? %>
                 <% @user.reviews.limit(10).each do |review| %>
                    <div class="user-review-container">
                      <p class="box-top">
                         <strong><span class="review-location-name"><%= link_to Location.find(review.location_id).name, location_path(review.location.id), 'data-no-turbolink' => true  %></span></strong> <%= review.date_added %>
                      </p>
                      <p class="stars">
                         <% review.rating.to_i.times do %>
                           <span class="glyphicon glyphicon-star"></span>
                         <% end %>
                      </p>
                      <p>
                         <span class="review-location-content"><%= review.content %></span>
                      </p>
                    </div>
                 <% end %>
              <% else %>
                <p> No reviews yet!</p>
              <% end %>
           </div>
         </div>
      </div>
      <!-- End of the User Activity Code Block -->

</div>
<!-- Yielded Content End -->