config/routes.rb
Rails.application.routes.draw do

  get "welcome" => "welcome#index"

  resources :reviews

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "loggedin" => "sessions#loggedin"
  delete 'sessions' => "sessions#destroy"


  resources :likes

  match 'auth/:provider/callback', to: 'sessions#create_facebook', via: [:get, :post]
  match 'auth/failure', to: redirect('login'), via: [:get, :post]
  # match 'signout', to: 'sessions#destroy_facebook', as: 'signout', via: [:get, :post]

  get 'about' => 'sessions#about'

  get "users/new" => "users#new"
  post "users" => "users#create"

  root 'welcome#index'

  get 'users/:id' => 'users#show'


   # CRUD Routes for Users and nested CRUD for reviews
   resources :users do
      resources :reviews
      end

  resources :locations




# Routes for all API views
  namespace :api do
    get 'locations_api/search_name' => 'locations_api#search_name'
    get 'locations_api/search_location' => 'locations_api#search_location'
    get 'locations_api/reviews/:id' => 'locations_api#reviews', as: :reviews
    get 'locations_api/yelp/:id' => 'locations_api#yelp', as: :yelp
    get 'locations_api/:id' => 'locations_api#show'
    resources :locations_api

  end



end

app/models/location.rb
class Location < ActiveRecord::Base
  has_many :reviews
  has_many :likes, dependent: :destroy
  belongs_to :category

  validates :name, :address, presence: true

  validates :address, format: { with: /\d{5,}/}

  geocoded_by :address

  after_validation :geocode, :if => :address_changed?

  def average_rating
    total = 0
    num_reviews = 0
    self.reviews.each do |review|
      total += review.rating
      num_reviews += 1
    end
    total = total / num_reviews
    total.ceil
  end

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    url = "https://maps.googleapis.com/maps/api/js?key="
    key = ENV['GOOGLE_MAPS']
    @endpoint = url + key

    @like = Like.new

    if params[:search].present?
      if params[:search_type] == "Name"
        @target = Location.where("LOWER(name) LIKE ?","%#{params[:search].downcase}%").first || nil
        if @target
          @locations = Location.near(@target.address, 10, :order => "distance").limit(9)
        else
          flash[:danger] = "No matches found!"
          @locations = nil
          @target = nil
        end
      elsif params[:search_type] == "Location"
        if Location.near(params[:search], 10)
          @locations = Location.near(params[:search], 10, :order => "distance").limit(9)
        else
          flash[:danger] = "No matches found!"
          @locations = Location.all
        end
      end
    else
      @locations = Location.all.limit(9) #Location Limited to 20
    end
  end

  def new
    @location = Location.new
  end

  def create
    @location = Location.create(location_params)
    if @location.save
      flash[:success] = "Your location was created!"
      redirect_to @location
    else
      flash[:danger] = @location.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def show
    url = "https://maps.googleapis.com/maps/api/js?key="
    key = ENV['GOOGLE_MAPS']
    @endpoint = url + key
    @location = Location.find(params[:id])
    @client = Yelp.client.business(@location.yelp_id)
  end

  def destroy
    flash[:danger] = "Your location has been deleted!"
    @location = Location.find(params[:id])
    @location.destroy
    redirect_to locations_path
  end

  private
  def location_params
    params.require(:location).permit(:name, :address, :latitude, :longitude, :yelp_id)
  end


end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/index.html.erb
<script type="text/javascript" src="<%= @endpoint %>"></script>

<div class="row">
   <div class="col-md-12">

      <!-- Flash messages -->
      <%= render 'layouts/flash' %>
      <!-- end of flash messages -->
  </div>
</div>

<div class="row">
  <div class="col-md-9">
    <h1>Search</h1>
      <form class="form-inline">
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Enter a name or location", class: "form-control enter-text" %>
        </div>
        <div class="checkbox">
            <label>
            <%= radio_button_tag(:search_type, "Name", true) %> Name
            </label>
        </div>
        <div class="checkbox">
            <%= radio_button_tag(:search_type, "Location") %>  Location
        </div>
        <div class="form-group">
          <%= submit_tag "Go!", :name => nil, class: 'btn btn-success' %>
        </div>
      </form>


    <div class="circle_map"id="map"></div>
    </div>

         <!-- NEARBY LOCATIONS code block -->
     <div class="col-md-3 locations-panel">
        <h2>Nearby locations</h2>
            <ul class="list-group">
              <% if @locations %>
                <% @locations.each do |location|%>
                  <%= link_to location_path(location), 'data-no-turbolink' => true do %>
                    <li class="list-group-item" id="<%= location.id %>">
                      <span class="location-name"><%= location.name %></span>
                      <% if location.reviews.any? %>
                         <% location.average_rating.to_i.times do %>
                           <span class="glyphicon glyphicon-star"></span>
                       <% end %>
                       <% end %>
                    </li>
                  <% end %>
              <% end %>
           </ul>
            
            <% end %>

            <%= link_to new_location_path, class: "add-location" do %>
              <button type="button" class="btn btn-success">Add Location</button>
            <% end %>


     </div> <!-- end location_panel -->

   </div> <!-- end col -->
</div> <!-- end row -->



<div class="modal fade" id="showModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" id="locations-modal">
    <div class="modal-content">
      <div class="modal-header text-center">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"></h4>
        <%= form_for @like do |f| %>
        <%= f.hidden_field :user_id, :value => current_user.id %>
        <%= f.hidden_field :location_id %>
        <%= f.submit "Add to favorites!", class: "btn btn-warning" %>
        <% end %>
      </div>
      <div class="modal-body text-center">
        <div id="myModalBody">
        <!-- Javascript Generated Content Here -->
        </div>
        <div id="addReviewBox">
          <a href="#" id="addReviewButton" class="btn btn-primary">Add a review!</a>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/locations/new.html.erb
<!-- This file contains code relating to the Location New Page -->

<!-- Begin Yielded Content -->

      <!-- Flash messages -->
      <%= render 'layouts/flash' %>
      <!-- end of flash messages -->
   <div class="newLocation col-xs-6 col-xs-offset-3">
      <h1 class="text-center">New Location</h1>
         <%= form_for @location, class: 'form-group' do |f| %>
            <%= f.text_field :name, class: "form-control", placeholder: "Name" %>
            <br>
            <%= f.text_field :address, class: "form-control", placeholder: "Street Address" %>
            <br>
            <%= f.text_field :yelp_id, class: "form-control", placeholder: "Location Yelp ID" %>
            <br>
            <%= f.submit "Submit", class: 'btn btn-primary' %>

            <%= link_to locations_path do %>
               <button type="button" class="btn btn-success">Back</button>
            <% end %>
      <% end %>
   </div>

app/views/locations/show.html.erb
<script type="text/javascript" src="<%= @endpoint %>"></script>
<!-- The code in this file pertains to the content of the Location Show Page -->

<!-- Begin Yielded Content -->

<div class="row">
  <div class="col-sm-12">
   <!-- Flash messages -->
     <%= render 'layouts/flash' %>
   <!-- end of flash messages -->
   </div>
</div>
   <!-- This code block sets a page content width of 10col and offset 1col -->
<div class="custom-container">
  <div class="row">
     <div class="col-sm-4">

        <!-- This div contains the Location INFO BOX about the specific location: name address phone etc -->

           <h1><%= @location.name %></h1>

           <p><strong>Address</strong>
             <%= @location.address %>
           </p>

           <% begin %>
             <% @client.display_phone %>
           <% rescue %>
           <% else %>
             <p><strong>Phone</strong>
               <%= @client.display_phone %>
             </p>
           <% end %>

           <!-- If the current user is an administrator, they have the ability to delete locations -->
           <% if current_user.admin? %>
           <%= link_to "Delete", @location, method: :delete, data: {confirm: "Are you sure you want to delete this location?"}, class: "btn btn-success" %>
           <% end %>
        <!-- End of Location INFO BOX -->
    </div>


    <div class="col-sm-8">
      <div class="small-map" id="map2"></div>
      </div>
    </div>
  </div> <!-- end row -->

  <div class="row gallery-row">

    <div class="col-sm-12">
      <h2 class="gallery-header">User Photos</h2>
        <div class="text-center">
        <% if @location.reviews.any? %>
             <% @location.reviews.each do |review| %>
             
              <div class="photo-gal-box">
              <%= image_tag review.photo.url, class: "photo-gal img-thumbnail" if review.photo? %>
              </div>
             
             <% end %>
        <% end %>
        <div class="photo-gal-box">
        <div class="photo-gal img-thumbnail">
          <div class=" add-photo">
          <p>Add a photo by leaving a review below!</p>
          <%= image_tag "white-camera.svg", class: "cam-icon" %>
          </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="row review-row-title">
    <div class="col-sm-12">
      <h2>Reviews</h2>
    </div>
  </div>
  
    <% if @location.reviews.any? %>
         <% @location.reviews.reverse.each do |review| %>
         <div class="row review-row-content">
          <div class="col-sm-3">
             <h4><%= User.find(review.user_id).username || User.find(review.user_id).name %></h4>
             <p class="review-date"><%= review.date_added %></p>
             <p class="review-stars"><% review.rating.to_i.times do %><span class="glyphicon glyphicon-star"></span><% end %></p>
             
          </div>
            <div class="col-sm-9 review-each-content">
              <p class=""><%= review.content %></p>
              <% if current_user.admin?  || review.user_id = current_user.id %>
              <%= link_to "Delete", review, method: :delete, data: {confirm: "Are you sure you want to delete this review?"}, class: "btn btn-success" %>
             <% end %>
            </div>
          </div>
        <% end %>
     <% else %>
        <div class="row no-review">
        <div class="col-sm-12">
       <p>No reviews yet! Be the first to add a review below!</p>
       </div>
       </div>
     <% end %>
    
     <div class="row add-review-header">
     <div class="col-sm-12">
     <h2>Share your Opinion!</h2>
     </div>
     </div>

    <div class="row">
      <div class="col-sm-10 col-sm-offset-1">
      
        
        <%= form_for [current_user, Review.new], :html => { :class => "form-horizontal" } do |f| %>
          <%= f.hidden_field :user_id, :value => current_user.id %>
          <%= f.hidden_field :location_id, :value => @location.id %>
          <div class="form-group">
            <%= f.label :rating, class: "col-sm-1 control-label"%>
            <div class="col-sm-11">
              <p><%= f.number_field(:rating, options = {in: 1...6}) %></p>
            </div>
          </div>

          <div class="form-group">
            <%= f.label :content, class: "col-sm-1 control-label"%>
            <div class="col-sm-11">
              <%= f.text_area :content, class: "form-control", rows: "10" %>
            </div>
          </div>

          <div class="form-group">
           <%= f.label :photo, class: "col-sm-1 control-label" %>
           <div class="col-sm-11">
             <%= f.file_field :photo %>
            </div>
          </div>


          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-11">
              <%= f.submit "Save", class: "btn btn-primary" %>
            </div>
          </div>
        <% end %>
      </div>
    </div>




    <div class="row text-center">
      <!-- Link to location path -->
        <%= link_to locations_path, 'data-no-turbolink' => true do %>
         <button type="button" class="btn btn-warning">Go Back</button>
        <% end %>
        </div>


   <!-- End page content -->

<!-- End of yielded content -->

</div><!-- end custom container -->

<script type="text/javascript">
  
  // initializes google maps into our app
  function initialize() {
    var lat;
    var long;

    $.get('/api/locations_api/' + <%= @location.id %>, function(data) {
      lat = data.latitude;
      long = data.longitude;

    }).done(function() {
      console.log(lat)
      var location = new google.maps.LatLng(lat, long);

      var marker = new google.maps.Marker({
        position: location,
        icon: "/assets/marker.svg",
        animation: google.maps.Animation.DROP,
      });


      // styling for my map
      var styles = [{"featureType":"landscape.natural","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"color":"#e0efef"}]},{"featureType":"poi","elementType":"geometry.fill","stylers":[{"visibility":"on"},{"hue":"#1900ff"},{"color":"#c0e8e8"}]},{"featureType":"road","elementType":"geometry","stylers":[{"lightness":100},{"visibility":"simplified"}]},{"featureType":"road","elementType":"labels","stylers":[{"visibility":"off"}]},{"featureType":"transit.line","elementType":"geometry","stylers":[{"visibility":"on"},{"lightness":700}]},{"featureType":"water","elementType":"all","stylers":[{"color":"#7dcdcd"}]}];

      // sets styling for a map
      var styledMap = new google.maps.StyledMapType(styles, {name: 'Styled Map'});

      // gives us predefined options for our map
      var mapOptions = {
        center: location,
        zoom: 8
      };

      //creates the map
      var map = new google.maps.Map(document.getElementById('map2'), mapOptions);

      //This adds styling into my map
      map.mapTypes.set('map_style', styledMap);

      map.setMapTypeId('map_style');

      marker.setMap(map);

      })

    }

  // Loads in Google maps on window load
  google.maps.event.addDomListener(window, 'load', initialize);

</script>