config/routes.rb
Rails.application.routes.draw do

  get "welcome" => "welcome#index"

  resources :reviews

  get "login" => "sessions#new"
  post "login" => "sessions#create"
  get "loggedin" => "sessions#loggedin"
  delete 'sessions' => "sessions#destroy"


  resources :likes

  match 'auth/:provider/callback', to: 'sessions#create_facebook', via: [:get, :post]
  match 'auth/failure', to: redirect('login'), via: [:get, :post]
  # match 'signout', to: 'sessions#destroy_facebook', as: 'signout', via: [:get, :post]

  get 'about' => 'sessions#about'

  get "users/new" => "users#new"
  post "users" => "users#create"

  root 'welcome#index'

  get 'users/:id' => 'users#show'


   # CRUD Routes for Users and nested CRUD for reviews
   resources :users do
      resources :reviews
      end

  resources :locations




# Routes for all API views
  namespace :api do
    get 'locations_api/search_name' => 'locations_api#search_name'
    get 'locations_api/search_location' => 'locations_api#search_location'
    get 'locations_api/reviews/:id' => 'locations_api#reviews', as: :reviews
    get 'locations_api/yelp/:id' => 'locations_api#yelp', as: :yelp
    get 'locations_api/:id' => 'locations_api#show'
    resources :locations_api

  end



end

app/views/layouts/_flash.html.erb
<!-- Flash messages -->
<% flash.each do |key, value| %>
  <div class="alert alert-<%=key %>" role="alert">
    <%= value %>
  </div>
<% end %>
<!-- end of flash messages -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sightly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.png' %>
<link href='https://fonts.googleapis.com/css?family=Lato|Roboto:400,500' rel='stylesheet' type='text/css'>
</head>

<body class="<%= controller_name %> <%= action_name %>">

  <nav class="navbar navbar-inverse">
    <div class="container-fluid">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed mobile-btn" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <% if current_user %>
          <%= link_to locations_path, class: "navbar-brand", 'data-no-turbolink' => true do %>
            <%= image_tag "logo-svg-white.svg", class: "logo" %>
          <% end %>
        <% else %>
          <%= link_to welcome_path, class: "navbar-brand" do %>
            <%= image_tag "logo-svg-white.svg", class: "logo" %>
          <% end %>
        <% end %>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %>

          <li class="dropdown">

            <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.username || current_user.name %> <span class="caret"></span></a>

             <ul class="dropdown-menu dropmen" role="menu">
               <!-- Link to Map Page -->
               <li><%= link_to "Places", locations_path, 'data-no-turbolink' => true %></li>
               <!-- Link to User Profile -->
               <li><%= link_to "Profile", user_path(current_user) %></li>
               <!-- Logs User out, redirects them to Splash Page -->
               <li><%= link_to "Logout", sessions_path, method: :delete %></li>
               <!--  -->
               <li><%= link_to "About", about_path %></li>
             </ul>
          </li>

          <% else %>

           <li><a id="signUpNav" href="#">Sign Up</a></li>

           <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Login<span class="caret"></span></a>
            <ul class="dropdown-menu login-form">
              <li>

                <%= form_tag('login', method: 'post') do %>
                  <div class="form-group">
                    <label for="email">Email</label>
                    <%= email_field_tag :email,nil,:placeholder => "Email", class: 'form-control' %>
                  </div>
                  <div class="form-group">
                    <label for="password">Password</label>
                    <%= password_field_tag :password,nil,:placeholder =>  'Password', class: 'form-control'%>
                  </div>
                  <%= submit_tag "Login", class: "btn btn-success" %>
                <% end %>
              </li>
 
              <li role="separator" class="divider"></li>
 
              <li>
                <%= link_to "/auth/facebook" do %>
                  <div class="btn btn-primary">
                    Login with Facebook
                  </div>
                <% end %>
              </li>
            </ul>
          </li>

         <% end %>


        </ul>
      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <div class="container-fluid">
      <%= yield %>
      </div>


</body>
</html>